# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'K:\Coding\Python\nbt work\Remedy Call Logging\MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(397, 249)
        MainWindow.setMaximumSize(QtCore.QSize(397, 249))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.filepath = QtGui.QLineEdit(self.centralwidget)
        self.filepath.setEnabled(False)
        self.filepath.setGeometry(QtCore.QRect(10, 10, 291, 20))
        self.filepath.setObjectName(_fromUtf8("filepath"))
        self.openMds = QtGui.QPushButton(self.centralwidget)
        self.openMds.setGeometry(QtCore.QRect(310, 10, 75, 23))
        self.openMds.setObjectName(_fromUtf8("openMds"))
        self.sdplus = QtGui.QLineEdit(self.centralwidget)
        self.sdplus.setGeometry(QtCore.QRect(100, 120, 101, 20))
        self.sdplus.setObjectName(_fromUtf8("sdplus"))
        self.urgency = QtGui.QLineEdit(self.centralwidget)
        self.urgency.setGeometry(QtCore.QRect(270, 120, 31, 20))
        self.urgency.setInputMask(_fromUtf8(""))
        self.urgency.setText(_fromUtf8(""))
        self.urgency.setObjectName(_fromUtf8("urgency"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 120, 51, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 81, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.endUserName = QtGui.QLineEdit(self.centralwidget)
        self.endUserName.setGeometry(QtCore.QRect(100, 150, 101, 20))
        self.endUserName.setObjectName(_fromUtf8("endUserName"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 81, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 81, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.affectedUsers = QtGui.QLineEdit(self.centralwidget)
        self.affectedUsers.setGeometry(QtCore.QRect(100, 180, 101, 20))
        self.affectedUsers.setObjectName(_fromUtf8("affectedUsers"))
        self.logIssue = QtGui.QPushButton(self.centralwidget)
        self.logIssue.setGeometry(QtCore.QRect(310, 180, 75, 23))
        self.logIssue.setObjectName(_fromUtf8("logIssue"))
        self.summary = QtGui.QPlainTextEdit(self.centralwidget)
        self.summary.setGeometry(QtCore.QRect(10, 40, 291, 71))
        self.summary.setObjectName(_fromUtf8("summary"))
        self.refresh = QtGui.QPushButton(self.centralwidget)
        self.refresh.setGeometry(QtCore.QRect(310, 60, 75, 23))
        self.refresh.setObjectName(_fromUtf8("refresh"))
        self.pullSubject = QtGui.QPushButton(self.centralwidget)
        self.pullSubject.setGeometry(QtCore.QRect(310, 90, 75, 23))
        self.pullSubject.setObjectName(_fromUtf8("pullSubject"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 40, 71, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 397, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSDPlus = QtGui.QMenu(self.menubar)
        self.menuSDPlus.setObjectName(_fromUtf8("menuSDPlus"))
        self.menuCreation_Menu = QtGui.QMenu(self.menuSDPlus)
        self.menuCreation_Menu.setObjectName(_fromUtf8("menuCreation_Menu"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setEnabled(True)
        self.actionSettings.setObjectName(_fromUtf8("actionSettings"))
        self.actionReset_Form = QtGui.QAction(MainWindow)
        self.actionReset_Form.setObjectName(_fromUtf8("actionReset_Form"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAttach_MDS_to_SDPlus_Record = QtGui.QAction(MainWindow)
        self.actionAttach_MDS_to_SDPlus_Record.setObjectName(_fromUtf8("actionAttach_MDS_to_SDPlus_Record"))
        self.actionUpdate_Group = QtGui.QAction(MainWindow)
        self.actionUpdate_Group.setObjectName(_fromUtf8("actionUpdate_Group"))
        self.actionUpdate_Subject = QtGui.QAction(MainWindow)
        self.actionUpdate_Subject.setObjectName(_fromUtf8("actionUpdate_Subject"))
        self.actionUpdate_Requester = QtGui.QAction(MainWindow)
        self.actionUpdate_Requester.setObjectName(_fromUtf8("actionUpdate_Requester"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setEnabled(True)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionUpdate_Status = QtGui.QAction(MainWindow)
        self.actionUpdate_Status.setObjectName(_fromUtf8("actionUpdate_Status"))
        self.actionUpdate_Urgency = QtGui.QAction(MainWindow)
        self.actionUpdate_Urgency.setObjectName(_fromUtf8("actionUpdate_Urgency"))
        self.actionUpdate_Group_and_Status = QtGui.QAction(MainWindow)
        self.actionUpdate_Group_and_Status.setObjectName(_fromUtf8("actionUpdate_Group_and_Status"))
        self.actionCreate_SDPlus_Record = QtGui.QAction(MainWindow)
        self.actionCreate_SDPlus_Record.setObjectName(_fromUtf8("actionCreate_SDPlus_Record"))
        self.actionUpdate_Group_Status_add_Note = QtGui.QAction(MainWindow)
        self.actionUpdate_Group_Status_add_Note.setObjectName(_fromUtf8("actionUpdate_Group_Status_add_Note"))
        self.actionUpdate_Group_Status_add_Note_Assign_myself = QtGui.QAction(MainWindow)
        self.actionUpdate_Group_Status_add_Note_Assign_myself.setObjectName(_fromUtf8("actionUpdate_Group_Status_add_Note_Assign_myself"))
        self.actionAssign_Myself = QtGui.QAction(MainWindow)
        self.actionAssign_Myself.setObjectName(_fromUtf8("actionAssign_Myself"))
        self.actionAdd_Note = QtGui.QAction(MainWindow)
        self.actionAdd_Note.setObjectName(_fromUtf8("actionAdd_Note"))
        self.menuFile.addAction(self.actionReset_Form)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSettings)
        self.menuFile.addAction(self.actionQuit)
        self.menuCreation_Menu.addAction(self.actionCreate_SDPlus_Record)
        self.menuSDPlus.addAction(self.actionUpdate_Group_Status_add_Note_Assign_myself)
        self.menuSDPlus.addAction(self.actionUpdate_Group_Status_add_Note)
        self.menuSDPlus.addAction(self.actionUpdate_Group_and_Status)
        self.menuSDPlus.addSeparator()
        self.menuSDPlus.addAction(self.actionAttach_MDS_to_SDPlus_Record)
        self.menuSDPlus.addAction(self.actionAdd_Note)
        self.menuSDPlus.addAction(self.actionAssign_Myself)
        self.menuSDPlus.addAction(self.actionUpdate_Group)
        self.menuSDPlus.addAction(self.actionUpdate_Requester)
        self.menuSDPlus.addAction(self.actionUpdate_Status)
        self.menuSDPlus.addAction(self.actionUpdate_Subject)
        self.menuSDPlus.addAction(self.actionUpdate_Urgency)
        self.menuSDPlus.addSeparator()
        self.menuSDPlus.addAction(self.menuCreation_Menu.menuAction())
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSDPlus.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Remedy Logging System", None))
        self.openMds.setText(_translate("MainWindow", "&Open MDS", None))
        self.openMds.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.label.setText(_translate("MainWindow", "Urgency:", None))
        self.label_2.setText(_translate("MainWindow", "SDPlus Number:", None))
        self.label_3.setText(_translate("MainWindow", "End User name:", None))
        self.label_4.setText(_translate("MainWindow", "Affected Users:", None))
        self.logIssue.setText(_translate("MainWindow", "Log Issue", None))
        self.refresh.setText(_translate("MainWindow", "&Refresh", None))
        self.pullSubject.setText(_translate("MainWindow", "Pull Subject", None))
        self.menuFile.setTitle(_translate("MainWindow", "&File", None))
        self.menuSDPlus.setTitle(_translate("MainWindow", "&SDPlus", None))
        self.menuCreation_Menu.setTitle(_translate("MainWindow", "&Creation Menu", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionSettings.setText(_translate("MainWindow", "S&ettings", None))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+E", None))
        self.actionReset_Form.setText(_translate("MainWindow", "&Reset Form", None))
        self.actionReset_Form.setShortcut(_translate("MainWindow", "Ctrl+R", None))
        self.actionQuit.setText(_translate("MainWindow", "&Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAttach_MDS_to_SDPlus_Record.setText(_translate("MainWindow", "&Attach MDS", None))
        self.actionUpdate_Group.setText(_translate("MainWindow", "Update &Group to \'Back Office Third Party/CSC\'", None))
        self.actionUpdate_Subject.setText(_translate("MainWindow", "Update Su&bject", None))
        self.actionUpdate_Requester.setText(_translate("MainWindow", "Update &Requester", None))
        self.actionAbout.setText(_translate("MainWindow", "&About", None))
        self.actionUpdate_Status.setText(_translate("MainWindow", "Update Status to \'&Hold - Awaiting Third Party\'", None))
        self.actionUpdate_Urgency.setText(_translate("MainWindow", "Update U&rgency", None))
        self.actionUpdate_Group_and_Status.setText(_translate("MainWindow", "Update Group and &Status", None))
        self.actionCreate_SDPlus_Record.setText(_translate("MainWindow", "Create SDPlus &Record", None))
        self.actionUpdate_Group_Status_add_Note.setText(_translate("MainWindow", "Update Group, Status, add &Note", None))
        self.actionUpdate_Group_Status_add_Note_Assign_myself.setText(_translate("MainWindow", "&Update Group, Status, add Note, Assign myself", None))
        self.actionAssign_Myself.setText(_translate("MainWindow", "Assign Myself", None))
        self.actionAdd_Note.setText(_translate("MainWindow", "Add Note (\"Logged to CSC\")", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

